export const USER_DEFAULT_PERMISSIONS = {
    PERMISSIONS_RESET_PASSWORD : 'PERMISSIONS_RESET_PASSWORD',
    PERMISSIONS_VERIFY : 'PERMISSIONS_VERIFY',
    PERMISSIONS_GET_USER_BY_ID : 'PERMISSIONS_GET_USER_BY_ID',
    PERMISSIONS_GET_ROUTES_ACCESSIBLE_BY_ID: 'PERMISSIONS_GET_ROUTES_ACCESSIBLE_BY_ID',
    PERMISSIONS_GET_ALL_USERS : 'PERMISSIONS_GET_ALL_USERS',
}

export const ALL_PERMISSIONS = {
    PERMISSIONS_RESET_PASSWORD : 'PERMISSIONS_RESET_PASSWORD',
    PERMISSIONS_VERIFY : 'PERMISSIONS_VERIFY',
    PERMISSIONS_GET_ALL_USERS : 'PERMISSIONS_GET_ALL_USERS',
    PERMISSIONS_CREATE_USER : 'PERMISSIONS_CREATE_USER',
    PERMISSIONS_DELETE_USER_BY_ID : 'PERMISSIONS_DELETE_USER_BY_ID',
    PERMISSIONS_GET_USER_BY_ID : 'PERMISSIONS_GET_USER_BY_ID',
    PERMISSIONS_CREATE_USER_ROUTES_ACCESSIBLE: "PERMISSIONS_CREATE_USER_ROUTES_ACCESSIBLE",
    PERMISSIONS_GET_ROUTES_ACCESSIBLE_BY_ID: 'PERMISSIONS_GET_ROUTES_ACCESSIBLE_BY_ID',
    PERMISSIONS_GET_ROUTES_ACCESSIBLE_ALL_USERS: 'PERMISSIONS_GET_ROUTES_ACCESSIBLE_ALL_USERS',
    PERMISSIONS_UPDATE_ROUTES_ACCESSIBLE: 'PERMISSIONS_UPDATE_ROUTES_ACCESSIBLE',
}

export const OPTIONAL_PERMISSIONS = [
    {
        value: 'PERMISSIONS_CREATE_USER',
        logicalTerm: 'Create User'
    }
]